name: Déploiement automatique de la documentation Dokka

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Permet de n'avoir qu'un seul déploiement en cours à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 1) Construction de la doc Dokka et dépôt dans un artefact GitHub
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Génération de la doc Dokka
        run: |
          ./gradlew dokkaHtml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: zmanim/build/dokka/html

  # 2) Déploiement de l'artefact sur GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      # L’URL finale sera disponible dans la sortie `page_url` (cf. steps plus bas)
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
