name: Publication de l'exemple sur GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Permet de n'avoir qu'un seul déploiement en cours à la fois
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # 1) Construction de l'exemple Kotlin/Compose et dépôt dans un artefact GitHub
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Construction de l'exemple Kotlin/Compose
        run: |
          ./gradlew :sample:composeApp:wasmJsBrowserDistribution

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: sample/composeApp/build/dist/wasmJs/ProductionExecutable

  # 2) Déploiement de l'artefact sur GitHub Pages
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/sample

    steps:
      - name: Déploiement sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: sample/composeApp/build/dist/wasmJs/ProductionExecutable
